trycatchdemo

==============
int marks[]=new int[5];
		
		try
		{
			System.out.println(2/2);
			marks[7]=68;
		}	
		catch(ArithmeticException | ArrayIndexOutOfBoundsException  exObj ) // call the proper catch block
		{
			System.out.println(exObj.getMessage());
			
		}
	=====================	
		userinputexample
		-----------------------
		scanner scanner = new Scanner(System.in);
		
          try
		{
			System.out.println("enter the value of number1 ");
			int number1 = scanner.nextInt();
			
			System.out.println("enter the value of number2 ");
			int number2 = scanner.nextInt();
			
			int result = number1/number2;
			System.out.println("Result = "+ result);
		}
		catch (ArithmeticException e) 
		{
			System.out.println("do not enter zero");
		}
		catch(InputMismatchException ex)
		{
			System.out.println("enter only digits");
		}